# Generated by Django 4.1.7 on 2023-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor', '0003_useraccount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
