# Generated by Django 4.1.7 on 2023-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor', '0006_useraccount_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('to_person', models.CharField(max_length=100)),
                ('from_person', models.CharField(max_length=100)),
                ('sender_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
