# Generated by Django 4.1.7 on 2023-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor', '0008_remove_usertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='total_amount',
            new_name='receiver_amount',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='sender_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
