# Generated by Django 4.1.7 on 2023-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor', '0010_useraccount_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='notification_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
