# Generated by Django 4.1.7 on 2023-03-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registor', '0012_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='notification_receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registor.useraccount'),
        ),
    ]
