# Generated by Django 4.1.7 on 2023-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor', '0016_usernotification_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='other_person',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
